name: invalid
description: A new Flutter package project.
version: 0.0.1
author: null
homepage: null

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  equatable: ^1.2.5
  intl: ^0.17.0
  flutter_bloc: ^7.1.0

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter