name: invalid
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.1
  equatable: ^2.0.3
  intl: ^0.17.0
  flutter_bloc: ^8.0.0

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
