name: invalid
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  equatable: ^2.0.5
  intl: ^0.17.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
